version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run: docker build -q -t codeblick/shopware-6:php-7.4 .
      - run: docker push codeblick/shopware-6:php-7.4

      - run: docker build -q -t codeblick/shopware-6:php-7.4-xdebug --build-arg WITH_XDEBUG=1 .
      - run: docker push codeblick/shopware-6:php-7.4-xdebug

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: docker
