version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Choose an appropriate base image with Docker support
    working_directory: ~/repo  # You can specify where to run commands
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock  # Ensures Docker commands communicate with the host Docker daemon
    mounts:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Mount the Docker socket

jobs:
  build_php:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            # PHP, Node versions, and Xdebug flag mappings
            PHP_VERSION=$1
            NODE_VERSION=$2
            XDEBUG_FLAG=$3

            # Image Tag: without Xdebug or with Xdebug
            if [ "$XDEBUG_FLAG" -eq 1 ]; then
              IMAGE_TAG="codeblick/shopware-6:php-${PHP_VERSION}-xdebug"
            else
              IMAGE_TAG="codeblick/shopware-6:php-${PHP_VERSION}"
            fi

            # Docker login and build
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker buildx create --use
            docker buildx build -q --platform linux/amd64,linux/arm64 -t $IMAGE_TAG \
              --build-arg PHP_VERSION=$PHP_VERSION \
              --build-arg NODE_VERSION=$NODE_VERSION \
              --build-arg WITH_XDEBUG=$XDEBUG_FLAG \
              --push .

  build_php_8_4:
    executor: docker-executor
    steps:
      - run:
          name: Build PHP 8.4 Without Xdebug
          command: |
            docker run --rm my-image-build-script 8.4 20.12.0 0
      - run:
          name: Build PHP 8.4 With Xdebug
          command: |
            docker run --rm my-image-build-script 8.4 20.12.0 1

  build_php_8_3:
    executor: docker-executor
    steps:
      - run:
          name: Build PHP 8.3 Without Xdebug
          command: |
            docker run --rm my-image-build-script 8.3 20.12.0 0
      - run:
          name: Build PHP 8.3 With Xdebug
          command: |
            docker run --rm my-image-build-script 8.3 20.12.0 1

  build_php_8_2:
    executor: docker-executor
    steps:
      - run:
          name: Build PHP 8.2 Without Xdebug
          command: |
            docker run --rm my-image-build-script 8.2 18.20.0 0
      - run:
          name: Build PHP 8.2 With Xdebug
          command: |
            docker run --rm my-image-build-script 8.2 18.20.0 1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_php_8_4:
          filters:
            branches:
              only:
                - main
      - build_php_8_3:
          filters:
            branches:
              only:
                - main
      - build_php_8_2:
          filters:
            branches:
              only:
                - main
