version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2024.02
    parameters:
      php_version:
        type: string
      node_version:
        type: string
      with_xdebug:
        type: string
    steps:
      - checkout

      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run: docker buildx create --use

      - run: |
          TAG="php-$<< parameters.php_version >>$([ $<< parameters.with_xdebug >> == '1' ] && echo '-xdebug' || echo '')"
          docker buildx build -q \
            --platform linux/amd64,linux/arm64 \
            -t codeblick/shopware-6:$TAG \
            --build-arg PHP_VERSION=$<< parameters.php_version >> \
            --build-arg NODE_VERSION=$<< parameters.node_version >> \
            --build-arg WITH_XDEBUG=$<< parameters.with_xdebug >> \
            --push .

workflows:
  build_and_push:
    jobs:
      - build:
          name: build_php_8_4
          php_version: "8.4"
          node_version: "20.12.0"
          with_xdebug: "0"
      - build:
          name: build_php_8_3
          php_version: "8.3"
          node_version: "20.12.0"
          with_xdebug: "0"
      - build:
          name: build_php_8_2
          php_version: "8.2"
          node_version: "18.20.0"
          with_xdebug: "0"
      - build:
          name: build_php_8_4_xdebug
          php_version: "8.4"
          node_version: "20.12.0"
          with_xdebug: "1"
      - build:
          name: build_php_8_3_xdebug
          php_version: "8.3"
          node_version: "20.12.0"
          with_xdebug: "1"
      - build:
          name: build_php_8_2_xdebug
          php_version: "8.2"
          node_version: "18.20.0"
          with_xdebug: "1"
    filters:
      branches:
        only:
          - main
