version: 2
jobs:
  build_php_84:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker buildx create --use
      - run: docker buildx build --platform linux/amd64,linux/arm64 -t codeblick/shopware-6:php-8.4 --build-arg PHP_VERSION=8.4 --build-arg NODE_VERSION=20.12.0 --push .

  build_php_84_xdebug:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker buildx create --use
      - run: docker buildx build --platform linux/amd64,linux/arm64 -t codeblick/shopware-6:php-8.4-xdebug --build-arg PHP_VERSION=8.4 --build-arg NODE_VERSION=20.12.0 --build-arg WITH_XDEBUG=1 --push .

  build_php_83:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker buildx create --use
      - run: docker buildx build --platform linux/amd64,linux/arm64 -t codeblick/shopware-6:php-8.3 --build-arg PHP_VERSION=8.3 --build-arg NODE_VERSION=20.12.0 --push .

  build_php_83_xdebug:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker buildx create --use
      - run: docker buildx build --platform linux/amd64,linux/arm64 -t codeblick/shopware-6:php-8.3-xdebug --build-arg PHP_VERSION=8.3 --build-arg NODE_VERSION=20.12.0 --build-arg WITH_XDEBUG=1 --push .

  build_php_82:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker buildx create --use
      - run: docker buildx build --platform linux/amd64,linux/arm64 -t codeblick/shopware-6:php-8.2 --build-arg PHP_VERSION=8.2 --build-arg NODE_VERSION=18.20.0 --push .

  build_php_82_xdebug:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker buildx create --use
      - run: docker buildx build --platform linux/amd64,linux/arm64 -t codeblick/shopware-6:php-8.2-xdebug --build-arg PHP_VERSION=8.2 --build-arg NODE_VERSION=18.20.0 --build-arg WITH_XDEBUG=1 --push .

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_php_84:
          context: docker
          filters:
            branches:
              only:
                - main
      - build_php_84_xdebug:
          context: docker
          filters:
            branches:
              only:
                - main
      - build_php_83:
          context: docker
          filters:
            branches:
              only:
                - main
      - build_php_83_xdebug:
          context: docker
          filters:
            branches:
              only:
                - main
      - build_php_82:
          context: docker
          filters:
            branches:
              only:
                - main
      - build_php_82_xdebug:
          context: docker
          filters:
            branches:
              only:
                - main
