version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run: docker build -q -t codeblick/shopware-6:php-8.4 --build-arg PHP_VERSION=8.4 --build-arg NODE_VERSION=20.12.0 .
      - run: docker push codeblick/shopware-6:php-8.4

      - run: docker build -q -t codeblick/shopware-6:php-8.3 --build-arg PHP_VERSION=8.3 --build-arg NODE_VERSION=20.12.0 .
      - run: docker push codeblick/shopware-6:php-8.3

      - run: docker build -q -t codeblick/shopware-6:php-8.2 --build-arg PHP_VERSION=8.2 --build-arg NODE_VERSION=18.20.0 .
      - run: docker push codeblick/shopware-6:php-8.2

      - run: docker build -q -t codeblick/shopware-6:php-8.1 --build-arg PHP_VERSION=8.1 --build-arg NODE_VERSION=16.20.2 .
      - run: docker push codeblick/shopware-6:php-8.1

      - run: docker build -q -t codeblick/shopware-6:php-8.0 --build-arg PHP_VERSION=8.0 --build-arg NODE_VERSION=16.20.2 .
      - run: docker push codeblick/shopware-6:php-8.0

      - run: docker build -q -t codeblick/shopware-6:php-8.4-xdebug --build-arg PHP_VERSION=8.4 --build-arg NODE_VERSION=20.12.0 --build-arg WITH_XDEBUG=1 .
      - run: docker push codeblick/shopware-6:php-8.4-xdebug

      - run: docker build -q -t codeblick/shopware-6:php-8.3-xdebug --build-arg PHP_VERSION=8.3 --build-arg NODE_VERSION=20.12.0 --build-arg WITH_XDEBUG=1 .
      - run: docker push codeblick/shopware-6:php-8.3-xdebug

      - run: docker build -q -t codeblick/shopware-6:php-8.2-xdebug --build-arg PHP_VERSION=8.2 --build-arg NODE_VERSION=18.20.0 --build-arg WITH_XDEBUG=1 .
      - run: docker push codeblick/shopware-6:php-8.2-xdebug

      - run: docker build -q -t codeblick/shopware-6:php-8.1-xdebug --build-arg PHP_VERSION=8.1 --build-arg NODE_VERSION=16.20.2 --build-arg WITH_XDEBUG=1 .
      - run: docker push codeblick/shopware-6:php-8.1-xdebug

      - run: docker build -q -t codeblick/shopware-6:php-8.0-xdebug --build-arg PHP_VERSION=8.0 --build-arg NODE_VERSION=16.20.2 --build-arg WITH_XDEBUG=1 .
      - run: docker push codeblick/shopware-6:php-8.0-xdebug

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: docker
          filters:
            branches:
              only:
                - main
