version: 2.1

executors:
  linux: # Linux executor for AMD images
    machine:
      image: ubuntu-latest
  macos: # macOS executor for ARM images
    macos:
      xcode: 16.2.0

jobs:
  build:
    parameters:
      os:
        type: executor
      platform:
        type: string
      php_version:
        type: string
      node_version:
        type: string
      with_xdebug:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout

      # Install Docker on macOS or Linux
      - run:
          name: Install Docker
          command: |
            if [ "<< parameters.os >>" == "macos" ]; then
              brew install docker
            else
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker buildx create --use

      - run: |
          TAG="php-$<< parameters.php_version >>$([ $<< parameters.with_xdebug >> == '1' ] && echo '-xdebug' || echo '')"
          docker buildx build -q \
            --platform $<< parameters.platform >> \
            -t codeblick/shopware-6:$TAG \
            --build-arg PHP_VERSION=$<< parameters.php_version >> \
            --build-arg NODE_VERSION=$<< parameters.node_version >> \
            --build-arg WITH_XDEBUG=$<< parameters.with_xdebug >> \
            --push .

workflows:
  build_and_push:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos]
              platform:
                - linux: "linux/amd64"
                  macos: "linux/arm64"
              php_version: ["8.2", "8.3", "8.4"]
              with_xdebug: ["0", "1"]
            include:
              - php_version: "8.2"
                node_version: "18.20.0"
              - php_version: "8.3"
                node_version: "20.12.0"
              - php_version: "8.4"
                node_version: "20.12.0"
          filters:
            branches:
              only:
                - main
