version: 2.1

parameters:
  platform:
    type: string
    default: "linux/amd64"
  php_version:
    type: string
    default: "8.2"
  with_xdebug:
    type: string
    default: "0"
  node_version:
    type: string
    default: "18.20.0"

jobs:
  build:
    parameters:
      platform:
        type: string
      php_version:
        type: string
      with_xdebug:
        type: string
      node_version:
        type: string
    docker:
      - image: cimg/base:2024.01
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Login to GHCR
          command: echo "$GHCR_TOKEN" | docker login ghcr.io --username $GHCR_USER --password-stdin

      - run:
          name: Set up Docker Buildx
          command: docker buildx create --use

      - run:
          name: Set up QEMU
          command: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - run:
          name: Build and push Docker image
          command: |
            TAG="php-$<< parameters.php_version >>$([ $<< parameters.with_xdebug >> == '1' ] && echo '-xdebug' || echo '')"
            docker buildx build \
              --platform $<< parameters.platform >> \
              -t codeblick/shopware-6:$TAG \
              -t ghcr.io/codeblick/shopware-6:$TAG \
              --build-arg PHP_VERSION=$<< parameters.php_version >> \
              --build-arg WITH_XDEBUG=$<< parameters.with_xdebug >> \
              --build-arg NODE_VERSION=$<< parameters.node_version >> \
              --push .

  merge:
    docker:
      - image: cimg/base:2024.01
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run:
          name: Login to GHCR
          command: echo "$GHCR_TOKEN" | docker login ghcr.io --username $GHCR_USER --password-stdin

      - run:
          name: Set up Docker Buildx
          command: docker buildx create --use

      - run:
          name: Create manifest list and push
          command: |
            docker buildx imagetools create \
              -t codeblick/shopware-6:php-8.2 \
              -t codeblick/shopware-6:php-8.3 \
              -t codeblick/shopware-6:php-8.4 \
              -t codeblick/shopware-6:php-8.2-xdebug \
              -t codeblick/shopware-6:php-8.3-xdebug \
              -t codeblick/shopware-6:php-8.4-xdebug \
              -t ghcr.io/codeblick/shopware-6:php-8.2 \
              -t ghcr.io/codeblick/shopware-6:php-8.3 \
              -t ghcr.io/codeblick/shopware-6:php-8.4 \
              -t ghcr.io/codeblick/shopware-6:php-8.2-xdebug \
              -t ghcr.io/codeblick/shopware-6:php-8.3-xdebug \
              -t ghcr.io/codeblick/shopware-6:php-8.4-xdebug

      - run:
          name: Inspect image
          command: |
            docker buildx imagetools inspect codeblick/shopware-6:php-8.2
            docker buildx imagetools inspect codeblick/shopware-6:php-8.3
            docker buildx imagetools inspect codeblick/shopware-6:php-8.4
            docker buildx imagetools inspect codeblick/shopware-6:php-8.2-xdebug
            docker buildx imagetools inspect codeblick/shopware-6:php-8.3-xdebug
            docker buildx imagetools inspect codeblick/shopware-6:php-8.4-xdebug
            docker buildx imagetools inspect ghcr.io/codeblick/shopware-6:php-8.2
            docker buildx imagetools inspect ghcr.io/codeblick/shopware-6:php-8.3
            docker buildx imagetools inspect ghcr.io/codeblick/shopware-6:php-8.4
            docker buildx imagetools inspect ghcr.io/codeblick/shopware-6:php-8.2-xdebug
            docker buildx imagetools inspect ghcr.io/codeblick/shopware-6:php-8.3-xdebug
            docker buildx imagetools inspect ghcr.io/codeblick/shopware-6:php-8.4-xdebug

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          matrix:
            parameters:
              platform: ["linux/amd64", "linux/arm64"]
              php_version: ["8.2", "8.3", "8.4"]
              with_xdebug: ["0", "1"]
              include:
                - php_version: "8.2"
                  node_version: "18.20.0"
                - php_version: "8.3"
                  node_version: "20.12.0"
                - php_version: "8.4"
                  node_version: "20.12.0"
          parallelism: 12
          filters:
            branches:
              only:
                - main
      - merge:
          requires:
            - build
          filters:
            branches:
              only:
                - main
