version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker buildx create --use

      - run: docker buildx build -q --platform linux/amd64,linux/arm64 -t codeblick/shopware-6:php-8.4 --build-arg PHP_VERSION=8.4 --build-arg NODE_VERSION=20.12.0 --push .

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: docker
          filters:
            branches:
              only:
                - main
