name: "Docker Build Push Retry"
description: "Composite action wrapping docker/build-push-action with retry logic."
inputs:
  platforms:
    description: "Platforms to build."
    required: true
  labels:
    description: "Docker build labels."
    required: false
  build_args:
    description: "Build arguments."
    required: false
  context:
    description: "Build context."
    default: "."
runs:
  using: composite
  steps:
    - name: Attempt 1
      id: attempt1
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.platforms }}
        labels: ${{ inputs.labels }}
        outputs: type=image,"name=${{ env.DOCKERHUB_REPO }}",push-by-digest=true,name-canonical=true,push=true
        build-args: ${{ inputs.build_args }}
        context: ${{ inputs.context }}
      continue-on-error: true

    - name: Attempt 2
      if: ${{ steps.attempt1.outcome != 'success' }}
      id: attempt2
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.platforms }}
        labels: ${{ inputs.labels }}
        outputs: type=image,"name=${{ env.DOCKERHUB_REPO }}",push-by-digest=true,name-canonical=true,push=true
        build-args: ${{ inputs.build_args }}
        context: ${{ inputs.context }}
      continue-on-error: true

    - name: Attempt 3
      if: ${{ steps.attempt1.outcome != 'success' && steps.attempt2.outcome != 'success' }}
      id: attempt3
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.platforms }}
        labels: ${{ inputs.labels }}
        outputs: type=image,"name=${{ env.DOCKERHUB_REPO }}",push-by-digest=true,name-canonical=true,push=true
        build-args: ${{ inputs.build_args }}
        context: ${{ inputs.context }}

    - name: Fail if all attempts failed
      if: ${{ steps.attempt1.outcome != 'success' && steps.attempt2.outcome != 'success' && steps.attempt3.outcome != 'success' }}
      run: |
        echo "All attempts to build and push the Docker image have failed."
        exit 1