name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  DOCKERHUB_REPO: codeblick/shopware-6
  GHCR_REPO: ghcr.io/codeblick/shopware-6

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        php_version:
          - "8.2"
          - "8.3"
          - "8.4"
        include:
          - php_version: "8.2"
            node_version: "18.20.0"
          - php_version: "8.3"
            node_version: "20.12.0"
          - php_version: "8.4"
            node_version: "20.12.0"
        with_xdebug:
          - "0"
          - "1"
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          php_version=${{ matrix.php_version }}
          with_xdebug=${{ matrix.with_xdebug }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          echo "PHP_VERSION=${php_version}" >> $GITHUB_ENV
          echo "WITH_XDEBUG=${with_xdebug}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}
            ${{ env.GHCR_REPO }}
          tags: |
            type=raw,value=php-${{ matrix.php_version }}${{ matrix.with_xdebug == '1' && '-xdebug' || '' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          #context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            WITH_XDEBUG=${{ matrix.with_xdebug }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:php-${{ matrix.php_version }}${{ matrix.with_xdebug == '1' && '-xdebug' || '' }}
            ${{ env.GHCR_REPO }}:php-${{ matrix.php_version }}${{ matrix.with_xdebug == '1' && '-xdebug' || '' }}

  merge:
    runs-on: macos-latest
    needs:
      - build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}
            ${{ env.GHCR_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Create manifest list and push
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKERHUB_REPO }}:php-%s ' *)
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.GHCR_REPO }}:php-%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ steps.meta.outputs.version }}
          docker buildx imagetools inspect ${{ env.GHCR_REPO }}:${{ steps.meta.outputs.version }}
