name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push PHP 8.4
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: codeblick/shopware-6:php-8.4
          build-args: |
            PHP_VERSION=8.4
            NODE_VERSION=20.12.0

      - name: Build and push PHP 8.4 xdebug
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: codeblick/shopware-6:php-8.4-xdebug
          build-args: |
            PHP_VERSION=8.4
            NODE_VERSION=20.12.0
            WITH_XDEBUG=1

      - name: Build and push PHP 8.3
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: codeblick/shopware-6:php-8.3
          build-args: |
            PHP_VERSION=8.3
            NODE_VERSION=20.12.0

      - name: Build and push PHP 8.3 xdebug
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: codeblick/shopware-6:php-8.3-xdebug
          build-args: |
            PHP_VERSION=8.3
            NODE_VERSION=20.12.0
            WITH_XDEBUG=1name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push PHP 8.2
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: codeblick/shopware-6:php-8.2
          build-args: |
            PHP_VERSION=8.2
            NODE_VERSION=18.20.0

      - name: Build and push PHP 8.2 xdebug
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: codeblick/shopware-6:php-8.2-xdebug
          build-args: |
            PHP_VERSION=8.2
            NODE_VERSION=18.20.0
            WITH_XDEBUG=1